### ISSUE TITLE
Internal error: null?

### ISSUE THREAD

**Issue by errenb** [riege/one-record-converter#3]
I took some XFWB out of current business flow. The return is "Internal error: null".

**Comment by juandiezgi** [comment]
Hello Martin, Im also getting the same error, 
regards, 
Juan Pablo

[XFWB_020-28536325_154325_1.txt](https://github.com/riege/one-record-converter/files/7589337/XFWB_020-28536325_154325_1.txt)

![image](https://user-images.githubusercontent.com/50321366/143057717-af357e27-6800-4788-b668-54840449acb1.png)

**Comment by mskopp** [comment]
Thank you @errenb - the difference is SpecifiedLogisticsTransportMovement.StageCode.ModeCode being present in xfwbshnk.txt but not in the others:

        <SpecifiedLogisticsTransportMovement>
            <StageCode>Main-Carriage</StageCode>
            <ModeCode>4</ModeCode>

Well the converter should be able to continue converting even if the ModeCode is not given. 
This is a bug and we will release a bugfix version.

**Comment by mskopp** [comment]
fixed in release 0.9.1 - but note that the converter web-site is not on 0.9.1 yet.
Converter web-site is in the making though…

**Comment by mskopp** [comment]
Web-site https://onerecord.riege.com/ also got updated.

**Comment by errenb** [comment]
Issue is solved. Thanks a lot Riege team!
